import {
  CalendarDays,
  MoonStar,
  Sun,
  House,
  Info,
  Heart,
  User,
  Store,
  CheckCheck,
  CircleX,
  Check,
  ChevronDown,
  ChevronUp,
  Star,
  ListFilter,
  ArrowDownWideNarrow,
  Share2,
  MapPinned,
  MessageCircleMore,
  AArrowDown,
  ChevronRight,
  ChevronLeft,
  MessageCircleHeart,
  Building2,
  Bell,
  TicketCheck,
  BadgeHelp,
  FileText,
  Award,
  SquarePen,
  Image,
  Mail,
  BookLock,
  SquareScissors,
  X,
  ThumbsUp,
  AlertTriangle,
  Trash2,
} from "lucide-react-native";
import { iconWithClassName } from "./iconWithClassName";

iconWithClassName(CalendarDays);
iconWithClassName(MoonStar);
iconWithClassName(Sun);
iconWithClassName(House);
iconWithClassName(Info);
iconWithClassName(Heart);
iconWithClassName(User);
iconWithClassName(Store);
iconWithClassName(CheckCheck);
iconWithClassName(CircleX);
iconWithClassName(Check);
iconWithClassName(ChevronDown);
iconWithClassName(ChevronUp);
iconWithClassName(Star);
iconWithClassName(ListFilter);
iconWithClassName(ArrowDownWideNarrow);
iconWithClassName(Share2);
iconWithClassName(MapPinned);
iconWithClassName(MessageCircleMore);
iconWithClassName(AArrowDown);
iconWithClassName(ChevronRight);
iconWithClassName(ChevronLeft);
iconWithClassName(MessageCircleHeart);
iconWithClassName(Building2);
iconWithClassName(Bell);
iconWithClassName(TicketCheck);
iconWithClassName(BadgeHelp);
iconWithClassName(FileText);
iconWithClassName(Award);
iconWithClassName(SquarePen);
iconWithClassName(Image);
iconWithClassName(Mail);
iconWithClassName(BookLock);
iconWithClassName(SquareScissors);
iconWithClassName(X);
iconWithClassName(ThumbsUp);
iconWithClassName(AlertTriangle);
iconWithClassName(Trash2);

export {
  Share2,
  MoonStar,
  CalendarDays,
  Sun,
  House,
  Info,
  Heart,
  User,
  Store,
  CheckCheck,
  CircleX,
  Check,
  ChevronDown,
  ChevronUp,
  Star,
  ListFilter,
  ArrowDownWideNarrow,
  MapPinned,
  MessageCircleMore,
  AArrowDown,
  ChevronRight,
  ChevronLeft,
  MessageCircleHeart,
  Building2,
  Bell,
  TicketCheck,
  BadgeHelp,
  FileText,
  Award,
  SquarePen,
  Image,
  Mail,
  BookLock,
  SquareScissors,
  X,
  ThumbsUp,
  AlertTriangle,
  Trash2,
};
