export const professionals = [
  {
    id: "prof_001",
    name: "María Pérez",
    status: "activo",
    email: "maria.perez@example.com",
    phoneNumber: "+1234567890",
    businessName: "Glamour Studio",
    likes: 120,
    completedReservations: 50,
    receivedComments: 35,
    rating: 4.5,
    urlPhoto:
      "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    workingHours: {
      monday: { start: 9, end: 18 },
      tuesday: { start: 9, end: 18 },
      wednesday: { start: 9, end: 18 },
      thursday: { start: 9, end: 18 },
      friday: { start: 9, end: 18 },
      saturday: { start: 10, end: 16 },
    },
  },
  {
    id: "prof_002",
    name: "Carlos García",
    status: "activo",
    email: "carlos.garcia@example.com",
    phoneNumber: "+1987654321",
    businessName: "Glamour Studio",
    likes: 80,
    completedReservations: 40,
    receivedComments: 25,
    rating: 4.0,
    urlPhoto:
      "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    workingHours: {
      monday: { start: 10, end: 19 },
      tuesday: { start: 10, end: 19 },
      wednesday: { start: 10, end: 19 },
      thursday: { start: 10, end: 19 },
      friday: { start: 10, end: 19 },
      saturday: { start: 10, end: 14 },
    },
  },
  {
    id: "prof_003",
    name: "Laura Martínez",
    status: "activo",
    email: "laura.martinez@example.com",
    phoneNumber: "+1122334455",
    businessName: "Glamour Studio",
    likes: 200,
    completedReservations: 100,
    receivedComments: 60,
    rating: 4.0,
    urlPhoto:
      "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    workingHours: {
      monday: { start: 8.5, end: 17.5 },
      tuesday: { start: 8.5, end: 17.5 },
      wednesday: { start: 8.5, end: 17.5 },
      thursday: { start: 8.5, end: 17.5 },
      friday: { start: 8.5, end: 17.5 },
      saturday: { start: 9, end: 15 },
    },
  },
  {
    id: "prof_004",
    name: "José Rodríguez",
    status: "activo",
    email: "jose.rodriguez@example.com",
    phoneNumber: "+1222333444",
    businessName: "Glamour Studio",
    likes: 150,
    completedReservations: 75,
    receivedComments: 50,
    rating: 4.5,
    urlPhoto:
      "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    workingHours: {
      monday: { start: 9, end: 18 },
      tuesday: { start: 9, end: 18 },
      wednesday: { start: 9, end: 18 },
      thursday: { start: 9, end: 18 },
      friday: { start: 9, end: 18 },
      saturday: { start: 10, end: 14 },
    },
  },
  {
    id: "prof_005",
    name: "Ana López",
    status: "activo",
    email: "ana.lopez@example.com",
    phoneNumber: "+1333444555",
    businessName: "Glamour Studio",
    likes: 95,
    completedReservations: 60,
    receivedComments: 45,
    rating: 3.5,
    urlPhoto:
      "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    workingHours: {
      monday: { start: 9, end: 18 },
      tuesday: { start: 9, end: 18 },
      wednesday: { start: 9, end: 18 },
      thursday: { start: 9, end: 18 },
      friday: { start: 9, end: 18 },
      saturday: { start: 9, end: 14 },
    },
  },
];
